// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"example.com/ical/timetype"
)

type Event struct {
	UUID        string              `json:"uuid"`
	Summary     string              `json:"summary"`
	Location    sql.NullString      `json:"location"`
	Description string              `json:"description"`
	Start       timetype.CustomTime `json:"start"`
	End         timetype.CustomTime `json:"end"`
	CreatedAt   timetype.CustomTime `json:"created_at"`
}
