// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"example.com/ical/timetype"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
  uuid, summary, location,
  description, timezone, all_day,
  start, end,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	UUID        string              `json:"uuid"`
	Summary     string              `json:"summary"`
	Location    sql.NullString      `json:"location"`
	Description string              `json:"description"`
	Timezone    string              `json:"timezone"`
	AllDay      bool                `json:"all_day"`
	Start       timetype.CustomTime `json:"start"`
	End         timetype.CustomTime `json:"end"`
	CreatedAt   timetype.CustomTime `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.UUID,
		arg.Summary,
		arg.Location,
		arg.Description,
		arg.Timezone,
		arg.AllDay,
		arg.Start,
		arg.End,
		arg.CreatedAt,
	)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE uuid = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, uuid)
	return err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT uuid, summary, location, description, timezone, all_day, start, "end", created_at FROM events
WHERE end > datetime('now')
ORDER BY start
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.UUID,
			&i.Summary,
			&i.Location,
			&i.Description,
			&i.Timezone,
			&i.AllDay,
			&i.Start,
			&i.End,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT uuid, summary, location, description, timezone, all_day, start, "end", created_at FROM events
WHERE end > datetime('now') AND uuid = ?
LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, uuid string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, uuid)
	var i Event
	err := row.Scan(
		&i.UUID,
		&i.Summary,
		&i.Location,
		&i.Description,
		&i.Timezone,
		&i.AllDay,
		&i.Start,
		&i.End,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET summary = ?, location = ?,
description = ?, timezone = ?, all_day = ?, start = ?, end = ?
WHERE uuid = ?
`

type UpdateEventParams struct {
	Summary     string              `json:"summary"`
	Location    sql.NullString      `json:"location"`
	Description string              `json:"description"`
	Timezone    string              `json:"timezone"`
	AllDay      bool                `json:"all_day"`
	Start       timetype.CustomTime `json:"start"`
	End         timetype.CustomTime `json:"end"`
	UUID        string              `json:"uuid"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.Summary,
		arg.Location,
		arg.Description,
		arg.Timezone,
		arg.AllDay,
		arg.Start,
		arg.End,
		arg.UUID,
	)
	return err
}
